more nginx prep

diff --git a/app/scripts/ship-launch b/app/scripts/ship-launch
--- a/app/scripts/ship-launch
+++ b/app/scripts/ship-launch
@@ -1,21 +1,23 @@
 #!/usr/bin/env bash
 ### Usage:
-###   ship-launch <workstation_name>
+###   ship-launch <hull_name> 
 ### Options:
 ###   --help
-###   <workstation_name>    name of the workstation
-###
-### Starts service operations in a workstation
 
 #--HEAD--
-set -o nounset; set -o errexit; set -o pipefail;
+# TODO: See if this can be added from a template
+set -o nounset; set -o errexit; set -o pipefail
 SCRIPT="$(test -L "$0" && readlink -e "$0" || readlink -e "$0")"
 SCRIPT_NAME="$(basename "${SCRIPT}")"
 SCRIPT_DIR="$(dirname "${SCRIPT}")"
 source "${SCRIPT_DIR}/main.source"
 #--/HEAD--
 
-if ! hull_exists "${workstation_name}"; then
-  fatal "invalid container name '${workstation_name}'"
+if ! hull_exists "${hull_name}"; then
+  echo "upstream ${hull_name} {" > "${UPSTREAM_CONF}"
+  for IP_ADDRESS in $(lxc-ls --fancy | grep "^${container_group}" | awk '{ print $3; }')
+  do
+    echo "server ${IP_ADDRESS}:${container_port} max_fails=0;" >> "${UPSTREAM_CONF}"
+  done
+  echo "}" >> "${UPSTREAM_CONF}"
 fi
-lxc-attach --name "${workstation_name}" -- sudo -H -u ubuntu -i bash -c "./start.sh"
